### ISSUE TITLE
Time info stored with other text

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#100]
Is it possible to extract time data if it is only stored as text with other text information as well (i.e. author text, header, etc.)? This is the case for a few of my URLs and no path I write seems to be successful at pulling it. Thanks!

**Comment by mikeizbicki** [comment]
It depends on how much other stuff there is.  If it's more than a couple of words, it probably won't work.

In that case, for the `human_annotator` field, insert `skip: date parser` so that the test case gets skipped and I know why it's being skipped.  The `golden.csv` file already has quite a few of these entries that I've been entering when I merge people's contributions.

**Comment by rayegleekel** [comment]
Okay, thank you! Should I change it to TRUE or leave as FALSE?
