### ISSUE TITLE
Installing langid on lambda server

### ISSUE THREAD

**Issue by DestrosCMC** [mikeizbicki/metahtml#134]
When installing the required libraries I run into this error because langid also installs numpy.
```
OSError: [Errno 122] Disk quota exceeded
```
How do I get around this?

**Comment by mikeizbicki** [comment]
First, to free up space on the lambda server, you'll need to delete the files that you've downloaded from pip install.  These files are stored in your `~/.local` folder, and so you should delete that folder.

Next, in order to get access to the libraries needed by metahtml, I've created a python "virtual environment" that has these libraries pre-installed.  You can enable the environment with the command
```
$ . /home/usertest/venv/bin/activate
```
The location `/home/usertest` is correct, and shouldnot be modified for your particular username.  After doing this, you should have access to all the needed libraries and be able to run the metahtml code.
