### ISSUE TITLE
timestamp.published configuration

### ISSUE THREAD

**Issue by Tonnpo** [mikeizbicki/metahtml#148]
Hi Mike,

I am specifically talking about this thai web page (https://www.nationthailand.com/business/30404054). The result from running 

```
python3 tests/test_golden.py 'https://www.nationthailand.com/business/30404054'
```
gives me

```
{
    "language": "en-th",
    "timestamp.modified": {
        "hi": "2021-04-22 23:06:29.999999+07:00",
        "lo": "2021-04-22 23:06:29+07:00"
    },
    "timestamp.published": {
        "hi": "2021-03-24 09:38:00.999999+07:00",
        "lo": "2021-03-24 09:38:00+07:00"
    },
    "type": "article",
    "url": "https://www.nationthailand.com/business/30404054"
}
```
However, if we go on the web page and scroll down to the bottom. I can see that it says 

> **Published : March 23, 2021** 

So, even with +07:00, it is still be on 2021-03-24. I believed the timestamp.published is based on GMT. So, if the published time on the web page infer to BKK time (GMT+07:00) , then it should say March 24, instead of March 23.
 Another possibility is that this website may use time conversion based on my timezone. Still, this should be 2021-03-24 09:38:00 - 07:00 equal to 2021-03-24 02:38:00 which is also on March, 24. 

I could misunderstood something and I could be wrong. So, could you please guide a way to get around with this? 

Thanks very much!

**Comment by mikeizbicki** [comment]
Great question!

There is a `--debug` flag that you can pass to `tests/test_golden.py` that will output additional information about how the library determined each of the metadata fields.  If you add that flag, you should get output similar to
```
...
"timestamp.published": {
        "best": {
            "is_valid_for_hostname": true,
            "parse_method": "dateutil",
            "pattern": "ld+json",
            "pattern_details": "$.datePublished",
            "raw": "2021-03-24T09:38:00+07:00",
            "value": {
                "hi": "2021-03-24 09:38:00.999999+07:00",
                "lo": "2021-03-24 09:38:00+07:00"
            }
        },
        "filtered": [
            {
                "is_valid_for_hostname": true,
                "parse_method": "dateutil",
                "pattern": "ld+json",
                "pattern_details": "$.datePublished",
                "raw": "2021-03-24T09:38:00+07:00",
                "value": {
                    "hi": "2021-03-24 09:38:00.999999+07:00",
                    "lo": "2021-03-24 09:38:00+07:00"
                }
            }
        ],
        "results": [
            {
                "is_valid_for_hostname": true,
                "parse_method": "dateutil",
                "pattern": "ld+json",
                "pattern_details": "$.datePublished",
                "raw": "2021-03-24T09:38:00+07:00",
                "value": {
                    "hi": "2021-03-24 09:38:00.999999+07:00",
                    "lo": "2021-03-24 09:38:00+07:00"
                }
            },
            {
                "is_valid_for_hostname": true,
                "parse_method": "dateutil",
                "pattern": "//meta[@*=\"article:published_time\"]/@content",
                "raw": "2021-03-24T09:38:00+07:00",
                "value": {
                    "hi": "2021-03-24 09:38:00.999999+07:00",
                    "lo": "2021-03-24 09:38:00+07:00"
                }
            }
        ]
...
```
The `results` portion of the output lists all of the locations in the document that publication times were found.  In this case, there's two found in the html's metainfo (one in the `ld+json` field and one in the html's `meta` tags).  There's three good reasons to trust these timestamp values over the March 23rd value:
1. these values match each other
2. these fields are always machine generated, and not human generated
3. they are more precise (minute level accuracy, rather than day accuracy)
Together, these indicate to me that this is the correct timestamp.

What likely happened is that there is just a small misconfiguration on the server somewhere that caused the publication date displayed to the user to be mismatched to the actual date.  If these dates were off by more than a day, then I'd be concerned, but being off by a day is really common with various timezone issues.

In general, if you use the `--debug` flag and get patterns that use `meta` or `ld+json`, and the output is within a day of something you see visually on the webpage, you can mark it as good.  If it was off by more, then I'd need to take a closer look on a case-by-case basis.

**Comment by Tonnpo** [comment]
This helps a lot! Thanks Mike!
