### ISSUE TITLE
Unexpected behavior from extracting category urls

### ISSUE THREAD

**Issue by Tonnpo** [mikeizbicki/metahtml#149]
Hi Mike,

I am specifically referring to this Thai website (https://www.thaipbs.or.th/home). I was testing this category url (https://program.thaipbs.or.th/MyanmarPolitics/stories). I expected no timestamp on the result. However, by running 
```
python3 tests/test_golden.py 'https://program.thaipbs.or.th/MyanmarPolitics/stories'
```
I got this result
```
{
    "language": "th-th",
    "timestamp.modified": {
        "hi": "2021-05-03 10:55:18.999999+07:00",
        "lo": "2021-05-03 10:55:18+07:00"
    },
    "timestamp.published": {
        "hi": "2021-02-14 15:18:36.999999+07:00",
        "lo": "2021-02-14 15:18:36+07:00"
    },
    "type": "article",
    "url": "https://program.thaipbs.or.th/MyanmarPolitics/stories"
}
```
Hence, I rerun the command with debug flag
```
python3 tests/test_golden.py 'https://program.thaipbs.or.th/MyanmarPolitics/stories' --debug
```
Then, the timestamp.published part gives me
```
"timestamp.published": {
        "best": {
            "is_valid_for_hostname": true,
            "parse_method": "dateutil",
            "pattern": "//meta[@*=\"og:published_time\"]/@content",
            "raw": "2021-02-14T15:18:36+07:00",
            "value": {
                "hi": "2021-02-14 15:18:36.999999+07:00",
                "lo": "2021-02-14 15:18:36+07:00"
            }
        },
        "filtered": [
            {
                "is_valid_for_hostname": true,
                "parse_method": "dateutil",
                "pattern": "//meta[@*=\"og:published_time\"]/@content",
                "raw": "2021-02-14T15:18:36+07:00",
                "value": {
                    "hi": "2021-02-14 15:18:36.999999+07:00",
                    "lo": "2021-02-14 15:18:36+07:00"
                }
            }
        ],
        "results": [
            {
                "is_valid_for_hostname": true,
                "parse_method": "dateutil",
                "pattern": "//meta[@*=\"og:published_time\"]/@content",
                "raw": "2021-02-14T15:18:36+07:00",
                "value": {
                    "hi": "2021-02-14 15:18:36.999999+07:00",
                    "lo": "2021-02-14 15:18:36+07:00"
                }
            }
        ]
    }
```
So, I inspected the web page to check where the information came from. Clearly, it comes from this tag
```
<meta property="og:published_time" content="2021-02-14T15:18:36+07:00">
```

In this case, would this published timestamp is of the web page itself, like when this web page is published or updated? And would this likely be the cause of falsely identifying this category url as article? If so, could you please advice on how to get around with this?

Thanks very much for your time and your help!

**Comment by mikeizbicki** [comment]
You're analysis is 100% correct.

The current procedure that metahtml follows is essentially: if something has a timestamp, it's an article; otherwise it's not.  There's a few minor exceptions to this rule.  For example, the root of a domain is always not an article, and if there's many different timestamps (I think >5), then it's not an article.  This is a very noisy procedure that needs to be fixed, but fixing it is a pretty hard problem.  I think it'll take some machine learning to fix the problem, and next week's reading paper actually addresses this problem too.  Depending on how things go over the next few weeks, this could be something you choose to try to tackle or not.

The basic idea at this point is just to add some exceptions to the rules above so that we get the test cases correctly recorded as not an article.  Then down the line, we'll have a good data set we could use to apply some machine learning to.

The code where the exceptions are located at is at: https://github.com/mikeizbicki/metahtml/blob/master/metahtml/property/type.py#L227  You can see a list of domain name/regex pairs.  Any url that matches the regex will be determined to be not an article.  So you want to write a regex that will match the url you found (and other similar categories if possible), but not any actual articles.

**Comment by Tonnpo** [comment]
I will try that. Thanks very much!
