### ISSUE TITLE
Language detection issue

### ISSUE THREAD

**Issue by Tonnpo** [mikeizbicki/metahtml#151]
Hi Mike,

I am referring to this specific website (https://www.posttoday.com/economy/news/653923). I ran the command
```
python3 tests/test_golden.py 'https://www.posttoday.com/economy/news/653923'
```
And got this result.
```
{
    "language": "en",
    "timestamp.modified": {
        "hi": "2021-05-26 12:37:49.999999+07:00",
        "lo": "2021-05-26 12:37:49+07:00"
    },
    "timestamp.published": {
        "hi": "2021-05-26 12:35:00.999999+07:00",
        "lo": "2021-05-26 12:35:00+07:00"
    },
    "type": "article",
    "url": "https://www.posttoday.com/economy/news/653923"
}
```
Clearly, this page contains Thai language. So, I ran the previous command with debug flag
```
python3 tests/test_golden.py 'https://www.posttoday.com/economy/news/653923' --debug
```
Then, the result of language part is
```
"language": {
        "best": {
            "is_valid_for_hostname": true,
            "pattern": "//html/@lang",
            "raw": "en",
            "value": "en"
        },
        "filtered": [
            {
                "is_valid_for_hostname": true,
                "pattern": "//html/@lang",
                "raw": "en",
                "value": "en"
            }
        ],
        "results": [
            {
                "is_valid_for_hostname": true,
                "pattern": "//html/@lang",
                "raw": "en",
                "value": "en"
            }
        ]
    },
```
Then, I go on and inspected the website and I saw this
```
<html lang="en">
```
So I checked language.py (in meta/property dir) and saw that it matched with `( None, '//html/@lang' )`. I believed that the developers who made this website might include `<html lang="en">` for some reasons. Therefore, is there any way that could be resolved on our end?

Thanks very much for your time and your help!

**Comment by mikeizbicki** [comment]
Good question.  It's fairly common actually for website developers to include wrong information in their websites like this, and I've had about 30 or so webpages with this problem that I haven't had a chance to add test cases for because of it.  But since you've run into the problem, that's given me the motivation to add a fix into the code, and now we can get these to work!

If you look at this section of code: https://github.com/mikeizbicki/metahtml/blob/master/metahtml/property/language.py#L87 you can see how I've added some special casing for handling these broken domains.  And I've added a case for the particular url you were working on too.

The only thing you'll have to be careful about is if there are multiple languages hosted on the same domain (or subdomains).  If that's the case, you should try to get test cases for each of the languages to ensure that it's properly detecting each of them.

**Comment by Tonnpo** [comment]
Got it, thanks!
