### ISSUE TITLE
Problems with Expressen.se

### ISSUE THREAD

**Issue by axelahdritz** [mikeizbicki/metahtml#165]
Hey Mike,

On this one popular Swedish magazine, I have been having some problems with the published timestamp. For instance, [this article](https://www.expressen.se/geo/folk-skriker-bara-rakt-ut-det-ar-som-en-film/) was published at `05:55` and yet the timestamp given reads `03:55`. See below:

'''
{
    "language": "sv-se",
    "timestamp.modified": {
        "hi": "2016-09-10 03:55:00.999999+00:00",
        "lo": "2016-09-10 03:55:00+00:00"
    },
    "timestamp.published": {
        "hi": "2016-09-10 03:55:00.999999+00:00",
        "lo": "2016-09-10 03:55:00+00:00"
    },
    "type": "article",
    "url": "https://www.expressen.se/geo/folk-skriker-bara-rakt-ut-det-ar-som-en-film/"
}
'''
This 2-hour time flaw is a common phenomenon on this webpage, and as such, I wrote an xPath that leads to the correct time, `//div[@class="article__meta"]/time`. How do I know whether the problem is fixed? Except for the two hour time difference, it seems to get everything else correct, so I am just wondering how to know when one has gotten it "right".

Additionally, as this is the first time writing an xPath, I was wondering if I should still make several `tests/.golden` file for the magazine or if I should just submit a pull request with the xPath changed alone?

Planning to cover several webpages today.

Best,
Axel

**Comment by mikeizbicki** [comment]
On this webpage, there is the following html tag:
```
<script type="application/ld+json">
{
    "@context": "http://schema.org",
    "@type": "NewsArticle",
    "url": "/geo/folk-skriker-bara-rakt-ut-det-ar-som-en-film/",
    "headline": "\u201dFolk skriker bara rakt ut. Det \u00e4r som en film\u201d",
    "thumbnailUrl": "https://static.cdn-expressen.se/images/86/f5/86f5bab8a8b94631807aa2d20d61b1f0/700@70.jpg",
    "dateCreated": "2016-09-10T03:55:00.000Z",
    "articleSection": "geo",
    "keywords": [],
    "author": [
        {
            "@type": "Person",
            "name": "magnus nystr\u00f6m"
        }
    ],
    "datePublished": "2016-09-10T03:55:00.000Z",
    "dateModified": "2016-09-10T03:55:00.000Z",
    "image": {
        "@type": "ImageObject",
        "url": "https://static.cdn-expressen.se/images/86/f5/86f5bab8a8b94631807aa2d20d61b1f0/700@70.jpg",
        "width": 700,
        "height": 395
    },
    "mainEntityOfPage": {
        "@type": "WebPage"
    },
    "publisher": {
        "@type": "Organization",
        "name": "Expressen AB",
        "logo": {
            "@type": "ImageObject",
            "url": "https://www.expressen.se/images/expressen-logo-for-sharing.png"
        }
    }
}
</script>
```
These `ld+json` script tags are one of the standard ways for documenting metadata about the webpage, and you can see that in there is a `datePublished` field.  That's the field that's being used to determine the publication date that you're seeing.  (You can determine this by passing the `--debug` flag to `test_golden.py`, and it will show the source of all of the information it extracts.)

The problem here is that the webpage has conflicting content about the publication date depending on where you look.  This stems from the fact that "publication date" is an ambiguous term.  Does it refer to when you saved the file?  Or when it was first put online?  Or when a link from the homepage was added so people can find it?  Or when you remove password protections so that non-editors can read it?  etc.  So not only can we not know which of these dates is the correct one to pick... in some sense there is no correct date... they're both equally correct.

When these problems arise, the important thing is just to check that the dates are "pretty close" to each other (basically same day is fine).  Then add the test case that this website passes.

What we don't want to have happen is the following:  Some webpages include these metadata tags not only for the current article, but also for lots of other articles on the webpage, and sometimes metahtml gets confused and tries to use the dates from these other articles as the dates for the current article.  This can result in the date being off by years, which will greatly distort any insights we can gain from the data.

> Additionally, as this is the first time writing an xPath, I was wondering if I should still make several tests/.golden file for the magazine or if I should just submit a pull request with the xPath changed alone?

In this case, no xpath is needed.  But in general, you should always be adding tests after you've verified that it works on a certain webpage.  It's not enough just to have verified it... we need actual evidence that it works, and that's what the test cases provide.

**Comment by WasabiWabiSabi** [comment]
Thank you so much. Super elucidating! It is good to know about the `--debug` flag, and I will definitely use it in the future.

**Comment by axelahdritz** [comment]
Hey Mike!

I encountered a strange phenomenon on this one other webpage that I was hoping you could elucidate. The webpage is an old one from 2008; [here](https://www.nsk.se/2008/08/08/loserville-tackar-for-sig/) is the link. `tests/test_golden.py` has no problem with other articles from this newspaper. See the output below: 
'''
{
    "timestamp.published": null,
    "type": "catalog",
    "url": "https://www.nsk.se/2008/08/08/loserville-tackar-for-sig/"
}
'''
After checking the json script tag, I was confused by the fact that there is in fact a `datePublished` field, but for some reason, `tests/test_golden.py` isn't picking it up. 

'''
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "NewsArticle",
  "headline": "Loserville tackar för sig",
  "mainEntityOfPage": {
    "@type": "WebPage",
    "@id": "https://www.nsk.se/2008/08/08/loserville-tackar-for-sig/"
  },
  "author": "Linda  Grip",
  "image": "https://imengine.public.prod.skd.infomaker.io?uuid=494d6926-99b3-4cae-bd36-047c6e4894e7&function=cropresize&type=preview&source=false&q=75&crop_w=0.99999&crop_h=0.82418&x=0&y=0.08791&width=980&height=551",
  "description": "- Vi började ju redan i slutet av 1900-talet, för att va lite vistsig.",
  "datePublished": "2008-08-08 12:00:00",
  "dateModified": "2008-08-08 12:00:00",
  "publisher": {
    "@type": "Organization",
    "name": "Skånska Dagbladet",
    "logo": {
      "@type": "ImageObject",
      "url": "https://www.nsk.se/wp-content/themes/everyware-theme-skd/assets/img/skanskanlogo16-9-white.jpg"
    }
  }
}
</script>
'''
How do I fix this issue?

Once this problem is fixed, all of the Swedish webpages on the `hostnames.csv` will have been covered, except for a few which were mirror images of each other (they were part of a larger local newspaper agency and were hosted on what seemed to be the same webpage format). I will then move onto Danish and Norwegian pages.

Best,
Axel

**Comment by mikeizbicki** [comment]
The line
```
    "type": "catalog",
```
comes from the fact that there are too many dates in the webpage.  Thus, it thinks that the webpage is not an article, but a catalog containing links to many different articles (something like "sports section" or "politics section" of a webpage).

For these webpages, you'll have to add the xpath to extract the date manually.
