### ISSUE TITLE
Issue when adding URLs to test_golden.py

### ISSUE THREAD

**Issue by peter-dimitrov** [mikeizbicki/metahtml#2]
When I try and add a URL to the test_golden.py file with this command:
```
$ python tests/test_golden.py --insert_urls https://apnews.com/766c1906bf954239988e6fe922e36821
```
I receive this error:

```$ python tests/test_golden.py --insert_urls https://apnews.com/766c1906bf954239988e6fe922e36821
Traceback (most recent call last):
  File "tests/test_golden.py", line 174, in <module>
    @pytest.mark.parametrize('test',get_golden_tests())
  File "tests/test_golden.py", line 158, in get_golden_tests
    for test in csv.DictReader(f, dialect='excel', strict=True):
  File "C:\Users\Peter\Anaconda3\lib\csv.py", line 111, in __next__
    self.fieldnames
  File "C:\Users\Peter\Anaconda3\lib\csv.py", line 98, in fieldnames
    self._fieldnames = next(self.reader)
  File "C:\Users\Peter\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1042: character maps to <undefined>
```

I believe it is because of the encoding of some of the characters in the titles (ex. Arabic, Greek). Any idea how to fix this issue?

Thanks

**Comment by mikeizbicki** [comment]
Are you using python2 or python3?  Python3 defaults to using utf-8 unicode encoding, which is how the files are encoded.

If you are using python3, then I recommend taking a look at https://docs.python.org/3/library/csv.html#examples to see how to adjust the code to use utf-8 by default (see the `encoding=` parameter).  I don't think I'll be able to fix this in the code for you, though, since I don't have access to your machine.
