### ISSUE TITLE
date time issues

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#30]
As you said in our Zoom call, I made the changes by adding the correct entries into the golden.csv file. Every time I opened the csv file in excel, excel changed the formatting of the dates, so I instead started using numbers which seems to maintain the formatting. But Travis is still saying that I have the wrong formatting of the date and time. Any idea what could be going wrong?

**Comment by mikeizbicki** [comment]
The string between the commas must exactly match what the program outputs in order for the test case to pass.  My guess is that excel is still not saving the file correctly for you.

You're welcome to try to continue to mess with the settings in excel to get it to behave correctly, but other students have started using libreoffice instead as it behaves correctly out of the box.  It's a free download on libreoffice.org.

**Comment by shashankvineet** [comment]
I tried using libreoffice, and when I open the csv file with libreoffice, it shows the correct formatting, but I don't know why Travis is saying that it's still failing. I even synced my forked repo with your original repo and started from scratch and created new entries for my URLs, but Travis is still giving me the same errors.

**Comment by mikeizbicki** [comment]
I've looked at the travis results.  It looks like you have fixed the csv issue that was causing the majority of the failures, as the failed test cases have gone from 50ish down to 4.  

In each of these remaining cases, your code is now saying that the webpage is not an article when the testcase says that it actually is.  My guess is that the code that you've added to `timestamp.py` worked for your hostnames, but caused these other hostnames to fail.  

Looking at the test case output, I can tell that in each case, too many dates are being found, and so the code is calling the page a `catalog` instead of an `article`.  Probably some of the xpaths you added are matching these hostnames as well?

**Comment by shashankvineet** [comment]
That's weird because the travis results show me that I'm still having the csv issues.

**Comment by mikeizbicki** [comment]
https://travis-ci.com/github/shashankvineet/metahtml shows only 4 tests failing
