### ISSUE TITLE
Merge conflict

### ISSUE THREAD

**Issue by shashankvineet** [mikeizbicki/metahtml#39]
As usual when I was syncing my forked repo with yours I ran into some merge conflicts. I was able to resolve the CONFLICT (content) ones, but there are 2 CONFLICT (add/add) conflicts that I'm not sure how to resolve. 

```
CONFLICT (add/add): Merge conflict in tests/.cache/https:||www.stripes.com|lifestyle|entertainment
Auto-merging tests/.cache/https:||www.stripes.com|downrange-troops-of-all-ranks-count-on-stripes-independence-1.184812
CONFLICT (add/add): Merge conflict in tests/.cache/https:||www.stripes.com|downrange-troops-of-all-ranks-count-on-stripes-independence-1.184812
```

**Comment by mikeizbicki** [comment]
You shouldn't try to resolve the merge conflict.  Because I had to rewrite your git history to remove the extra commits, this will be a difficult process to do correctly.  (You would also have to rewrite your history to remove those commits.)

The easiest thing to do is to just delete your repo, refork and clone to ensure that you don't have the old history.
