### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#80]
After manually inputting "TRUE" and the title for a paper publication, every time I run the insert_urls command I get the following error message: 
```Traceback (most recent call last):
  File "tests/test_golden.py", line 289, in <module>
    @pytest.mark.parametrize('test',get_golden_tests())
  File "tests/test_golden.py", line 272, in get_golden_tests
    for test in csv.DictReader(f, dialect='excel', strict=True):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/csv.py", line 112, in __next__
    row = next(self.reader)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 8134: invalid start byte
```
Any idea what happened and what I need to do? Thank you!

**Comment by mikeizbicki** [comment]
Most likely the `golden.csv` has been corrupted by having been saved in a format
that is not utf-8.  (I think you might have had similar errors before when using
Excel.)  

If that's the case, I don't think it would have happened because of manually
changing values in the spreadsheet, though, and it's probably just a coincidence
that it happened at the same time.  I've never had this problem when using
either libreoffice or vim to edit the file.

To fix it, you'll have to redownload the `golden.csv` file, then manually copy
over the lines that you've changed from the corrupted file to the new file.

**Comment by rayegleekel** [comment]
Hmm that is weird because when I deleted what I manually had put in and it started working again. Just to clarify, when I have a webpage that reads false because it is an encyclopedia type entry or text without a date, I should manually change that URL to "TRUE" and then input the title? Should I add my name to the human_annotator of these columns or say skip?

**Comment by mikeizbicki** [comment]
Interesting.  You're correct that's what you're supposed to do.  If the title
has special characters in it, like quotation marks or dashes, those could be
causing the issue somehow.  Maybe if you type out the title manually rather than
copy/paste it might work.

**Comment by rayegleekel** [comment]
The error seems to happen after I manually enter one specific URL's info. Should I just make a note of this and leave it as FALSE and without title?

**Comment by mikeizbicki** [comment]
Can you set it to `TRUE` without a title?

It's important that the test case fails, or it will probably get lost and I
won't see it again.

If that doesn't work, make a note in the pull request, but highlight it in bold
so that I'm sure not to miss it.

**Comment by rayegleekel** [comment]
Yes, that works. It seem to just be the title.

**Comment by rayegleekel** [comment]
Now, this is happening whenever I manually input a title. Should I just right TRUE for all of the URLs I have to manually change and leave out a title? I can also zoom to try to figure it out at any time today, if you are available. Thanks!

**Comment by mikeizbicki** [comment]
Just leaving out the titles is fine.

**Comment by maxinebaghdadi** [comment]
Circling back to this, I am having the same issue that Raye was having. The exact error that I am receiving is: 

`ests/test_golden.py:289: in <module>
    @pytest.mark.parametrize('test',get_golden_tests())
tests/test_golden.py:272: in get_golden_tests
    for test in csv.DictReader(f, dialect='excel', strict=True):
../anaconda3/lib/python3.6/csv.py:111: in __next__
    self.fieldnames
../anaconda3/lib/python3.6/csv.py:98: in fieldnames
    self._fieldnames = next(self.reader)
../anaconda3/lib/python3.6/codecs.py:321: in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
E   UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 2545: invalid continuation byte
`

The reason I'm confused is because I have been working in Libre Office. Would it be because others might have been working in Excel with utf-16? I'm not sure I understand what you meant about redownloading the file. Do you mean delete it from my current metahtml folder and add a new one in? 

Thanks :)
