### ISSUE TITLE
Pulling from your updated repository

### ISSUE THREAD

**Issue by rayegleekel** [mikeizbicki/metahtml#89]
When I ran the commands ```git remote add upstream https://github.com/mikeizbicki/metahtml``` and then ```git pull upstream master```, I got the following error message: 

```
Auto-merging tests/golden.csv
CONFLICT (content): Merge conflict in tests/golden.csv
Auto-merging metahtml/timestamp.py
CONFLICT (content): Merge conflict in metahtml/timestamp.py
Automatic merge failed; fix conflicts and then commit the result.
```
However, after I ran these commands the week5 url files showed up in my repo, which makes me think it worked. Do I need to do anything to fix this error? Thanks!

**Comment by mikeizbicki** [comment]
You are in the middle of a merge conflict right now.  If you run `git status`, you will see that it talks about unmerged files.  This happened because I was unable to directly merge you pull request and had to rewrite your git history when merging.  The easiest way to fix this is to refork and reclone.
